### ISSUE TITLE
Wrong name inside Window Decoration

### ISSUE THREAD

**Issue by Girtablulu** [alex47/BreezeBlurred#10]
Hi

Great work but I have a issue on Solus.

I packaged it for testing and the theme is called inside the Window Decoration "Breeze" and not "BreezeBlur", so I have right now two Breeze themes inside it, so it was a bit confusing.

Everything else is working as intended, the configuration tool has the correct naming.

Another question is could you do a official release? With an official release I could make a request to include it into the Solus repo :)

**Comment by alex47** [comment]
Could you please point out where the theme refers to itself as "Breeze"?
A link to the code or maybe a screenshot, so I can fix this easier?
What do you mean by official release?

**Comment by Girtablulu** [comment]
Hi

Sorry could have added a screenshot from the beginning 

https://i.imgur.com/LuI8BHi.png

With official release I'm talking about having a tar.gz to download, Solus package police requires a packages being out of beta and having a official release tar to download

**Comment by alex47** [comment]
I see you are not running with the english language. That's why it showed you the name Breeze.
I updated the name for all languages to "BreezeBlurred".
Also please notice that it was previously incorrectly called "BreezeBlur", so if you install it again you will have a "BreezeBlur" (or in your case a second "Breeze") theme and a new "BreezeBlurred" theme.

**Comment by Girtablulu** [comment]
Thanks for the quick fix :) now the name is correct
